// Liste curée d'émojis pertinents pour skalcook (resto / cuisine / gestion).
// Chaque émoji a des tags pour la recherche textuelle (sans accent, en minuscules).
// Organisé en groupes pour faciliter la navigation visuelle.
//
// Pour étendre : ajouter une entrée dans le groupe pertinent. Pas besoin de
// liste exhaustive — on privilégie la pertinence métier (~150 émojis suffisent).

export const EMOJI_GROUPS = [
  {
    id: 'cuisine',
    label: 'Cuisine',
    icon: '🍽',
    items: [
      { e: '🍽', tags: 'plat assiette repas' },
      { e: '🥗', tags: 'salade entree legume' },
      { e: '🥘', tags: 'paella plat cuisine' },
      { e: '🍲', tags: 'soupe pot' },
      { e: '🫕', tags: 'fondue raclette' },
      { e: '🍳', tags: 'oeuf poele' },
      { e: '🥞', tags: 'pancake crepe' },
      { e: '🥪', tags: 'sandwich' },
      { e: '🌮', tags: 'taco mexicain' },
      { e: '🌯', tags: 'burrito wrap' },
      { e: '🥙', tags: 'kebab pita' },
      { e: '🍔', tags: 'burger hamburger' },
      { e: '🍕', tags: 'pizza' },
      { e: '🍟', tags: 'frites' },
      { e: '🌭', tags: 'hot dog saucisse' },
      { e: '🍝', tags: 'pates spaghetti' },
      { e: '🍜', tags: 'ramen nouilles' },
      { e: '🍣', tags: 'sushi' },
      { e: '🍱', tags: 'bento japonais' },
      { e: '🍛', tags: 'curry riz' },
      { e: '🍚', tags: 'riz' },
      { e: '🍙', tags: 'onigiri' },
      { e: '🥟', tags: 'dumpling raviolis' },
      { e: '🥠', tags: 'fortune cookie' },
    ],
  },
  {
    id: 'viandes',
    label: 'Viandes & Poissons',
    icon: '🥩',
    items: [
      { e: '🥩', tags: 'viande steak boeuf' },
      { e: '🍖', tags: 'viande os' },
      { e: '🍗', tags: 'poulet volaille cuisse' },
      { e: '🥓', tags: 'bacon lard' },
      { e: '🐟', tags: 'poisson' },
      { e: '🐠', tags: 'poisson tropical' },
      { e: '🦐', tags: 'crevette' },
      { e: '🦞', tags: 'homard' },
      { e: '🦀', tags: 'crabe' },
      { e: '🦑', tags: 'calamar encornet' },
      { e: '🐙', tags: 'poulpe pieuvre' },
      { e: '🦪', tags: 'huitre fruits de mer' },
    ],
  },
  {
    id: 'legumes',
    label: 'Légumes',
    icon: '🥕',
    items: [
      { e: '🥕', tags: 'carotte' },
      { e: '🥔', tags: 'pomme de terre patate' },
      { e: '🍅', tags: 'tomate' },
      { e: '🍆', tags: 'aubergine' },
      { e: '🥒', tags: 'concombre cornichon' },
      { e: '🥬', tags: 'salade laitue' },
      { e: '🥦', tags: 'brocoli' },
      { e: '🌽', tags: 'mais epi' },
      { e: '🌶', tags: 'piment' },
      { e: '🫑', tags: 'poivron' },
      { e: '🧄', tags: 'ail' },
      { e: '🧅', tags: 'oignon' },
      { e: '🍄', tags: 'champignon' },
      { e: '🥑', tags: 'avocat' },
      { e: '🫘', tags: 'haricot legume sec' },
      { e: '🌱', tags: 'herbe pousse germe' },
      { e: '🌿', tags: 'herbe aromatique persil' },
    ],
  },
  {
    id: 'fruits',
    label: 'Fruits',
    icon: '🍎',
    items: [
      { e: '🍎', tags: 'pomme rouge' },
      { e: '🍏', tags: 'pomme verte' },
      { e: '🍐', tags: 'poire' },
      { e: '🍊', tags: 'orange clementine' },
      { e: '🍋', tags: 'citron' },
      { e: '🍌', tags: 'banane' },
      { e: '🍉', tags: 'pasteque' },
      { e: '🍇', tags: 'raisin' },
      { e: '🍓', tags: 'fraise' },
      { e: '🫐', tags: 'myrtille' },
      { e: '🍒', tags: 'cerise' },
      { e: '🍑', tags: 'peche' },
      { e: '🥭', tags: 'mangue' },
      { e: '🍍', tags: 'ananas' },
      { e: '🥥', tags: 'noix de coco' },
      { e: '🥝', tags: 'kiwi' },
      { e: '🍈', tags: 'melon' },
    ],
  },
  {
    id: 'boissons',
    label: 'Boissons',
    icon: '🍷',
    items: [
      { e: '🍷', tags: 'vin verre' },
      { e: '🥂', tags: 'champagne flute' },
      { e: '🍾', tags: 'bouteille champagne' },
      { e: '🍺', tags: 'biere' },
      { e: '🍻', tags: 'bieres trinquer' },
      { e: '🍸', tags: 'cocktail martini' },
      { e: '🍹', tags: 'cocktail tropical' },
      { e: '🥃', tags: 'whisky verre' },
      { e: '🍶', tags: 'sake' },
      { e: '☕', tags: 'cafe' },
      { e: '🍵', tags: 'the matcha' },
      { e: '🥤', tags: 'soda gobelet' },
      { e: '🧃', tags: 'jus brique' },
      { e: '🧊', tags: 'glacon glace' },
      { e: '🥛', tags: 'lait' },
      { e: '🍼', tags: 'biberon' },
      { e: '💧', tags: 'eau goutte' },
    ],
  },
  {
    id: 'desserts',
    label: 'Desserts & Sucré',
    icon: '🍰',
    items: [
      { e: '🍰', tags: 'gateau part' },
      { e: '🎂', tags: 'gateau anniversaire' },
      { e: '🧁', tags: 'cupcake muffin' },
      { e: '🍮', tags: 'flan creme caramel' },
      { e: '🍩', tags: 'donut beignet' },
      { e: '🍪', tags: 'cookie biscuit' },
      { e: '🥐', tags: 'croissant viennoiserie' },
      { e: '🥖', tags: 'baguette pain' },
      { e: '🍞', tags: 'pain mie' },
      { e: '🥨', tags: 'bretzel' },
      { e: '🍫', tags: 'chocolat tablette' },
      { e: '🍬', tags: 'bonbon' },
      { e: '🍭', tags: 'sucette' },
      { e: '🍯', tags: 'miel pot' },
      { e: '🍨', tags: 'glace coupe' },
      { e: '🍧', tags: 'glace pilee' },
      { e: '🍦', tags: 'glace cornet' },
      { e: '🥧', tags: 'tarte' },
    ],
  },
  {
    id: 'lieux',
    label: 'Lieux & Service',
    icon: '🏨',
    items: [
      { e: '🏨', tags: 'hotel' },
      { e: '🛎', tags: 'reception service cloche' },
      { e: '🌅', tags: 'matin petit dejeuner brunch' },
      { e: '🌃', tags: 'nuit soir diner' },
      { e: '🎭', tags: 'evenement spectacle' },
      { e: '🌊', tags: 'mer plage' },
      { e: '🏔', tags: 'montagne' },
      { e: '🌿', tags: 'terrasse jardin' },
      { e: '🪴', tags: 'plante decoration' },
      { e: '🌳', tags: 'arbre exterieur' },
      { e: '☀️', tags: 'soleil terrasse' },
      { e: '⛱', tags: 'parasol plage' },
      { e: '🏖', tags: 'plage' },
      { e: '🪑', tags: 'chaise' },
      { e: '🛋', tags: 'salon canape lounge' },
    ],
  },
  {
    id: 'utiles',
    label: 'Utiles',
    icon: '⭐',
    items: [
      { e: '⭐', tags: 'etoile favori' },
      { e: '✨', tags: 'etoiles brillant special' },
      { e: '🏷', tags: 'etiquette prix' },
      { e: '📦', tags: 'colis carton stockage' },
      { e: '🗂', tags: 'classeur dossier' },
      { e: '📋', tags: 'presse papier liste' },
      { e: '📝', tags: 'note ecriture' },
      { e: '🧾', tags: 'recu facture' },
      { e: '💰', tags: 'argent sac' },
      { e: '💶', tags: 'euro billet' },
      { e: '🛒', tags: 'panier courses' },
      { e: '🛍', tags: 'sac shopping' },
      { e: '⚙️', tags: 'parametre reglage' },
      { e: '🔧', tags: 'cle outil reparation' },
      { e: '🔥', tags: 'feu chaud' },
      { e: '❄️', tags: 'froid neige congelation' },
      { e: '⚡', tags: 'eclair energie' },
      { e: '🌶', tags: 'epice piment' },
      { e: '🧂', tags: 'sel poivre' },
      { e: '🥄', tags: 'cuillere' },
      { e: '🍴', tags: 'couverts fourchette couteau' },
      { e: '🔪', tags: 'couteau' },
    ],
  },
]

// Index plat pour la recherche : aplatit tous les groupes en une seule liste
// avec leur tag. Calculé une seule fois au module load.
export const ALL_EMOJIS = EMOJI_GROUPS.flatMap(g =>
  g.items.map(item => ({ ...item, groupId: g.id }))
)
