// Liste curée d'émojis groupés par thème, alignée sur les besoins de skalcook
// (resto / cuisine / gestion / général). ~600 émojis taggés en français pour
// la recherche textuelle (sans accent, lowercase).
//
// Pour étendre : ajouter une entrée { e, tags } dans le groupe pertinent.
// Pour créer un nouveau groupe : ajouter un objet dans EMOJI_GROUPS avec un
// id, un label, une icône (l'émoji affiché dans l'onglet) et la liste items.

export const EMOJI_GROUPS = [
  // ─── Plats & Préparations ──────────────────────────────────────────────────
  {
    id: 'cuisine',
    label: 'Plats',
    icon: '🍽',
    items: [
      { e: '🍽', tags: 'plat assiette repas' },
      { e: '🍴', tags: 'couverts fourchette couteau' },
      { e: '🥄', tags: 'cuillere' },
      { e: '🔪', tags: 'couteau' },
      { e: '🥢', tags: 'baguettes asiatique' },
      { e: '🥗', tags: 'salade entree legume' },
      { e: '🥘', tags: 'paella plat cuisine' },
      { e: '🍲', tags: 'soupe pot' },
      { e: '🍳', tags: 'oeuf poele' },
      { e: '🍕', tags: 'pizza' },
      { e: '🍔', tags: 'burger hamburger' },
      { e: '🌭', tags: 'hot dog saucisse' },
      { e: '🥪', tags: 'sandwich' },
      { e: '🌮', tags: 'taco mexicain' },
      { e: '🌯', tags: 'burrito wrap' },
      { e: '🥙', tags: 'kebab pita falafel' },
      { e: '🫔', tags: 'tamale mexicain' },
      { e: '🥟', tags: 'dumpling raviolis' },
      { e: '🥠', tags: 'fortune cookie' },
      { e: '🍜', tags: 'ramen nouilles soupe' },
      { e: '🍝', tags: 'pates spaghetti' },
      { e: '🍣', tags: 'sushi' },
      { e: '🍱', tags: 'bento japonais' },
      { e: '🍛', tags: 'curry riz' },
      { e: '🍚', tags: 'riz' },
      { e: '🍙', tags: 'onigiri boule de riz' },
      { e: '🍘', tags: 'cracker riz galette' },
      { e: '🥡', tags: 'plat a emporter takeaway' },
      { e: '🫕', tags: 'fondue raclette' },
      { e: '🍟', tags: 'frites' },
      { e: '🥞', tags: 'pancake crepe' },
      { e: '🧇', tags: 'gaufre' },
      { e: '🍿', tags: 'popcorn' },
      { e: '🧆', tags: 'falafel' },
      { e: '🫓', tags: 'pain plat naan tortilla' },
      { e: '🍢', tags: 'brochette oden' },
      { e: '🍡', tags: 'dango brochette japonaise' },
    ],
  },

  // ─── Viandes, Poissons, Charcuterie ────────────────────────────────────────
  {
    id: 'proteines',
    label: 'Viandes & Poissons',
    icon: '🥩',
    items: [
      { e: '🥩', tags: 'viande steak boeuf entrecote' },
      { e: '🍖', tags: 'viande os gigot' },
      { e: '🍗', tags: 'poulet volaille cuisse' },
      { e: '🥓', tags: 'bacon lard' },
      { e: '🌭', tags: 'saucisse hot dog' },
      { e: '🍤', tags: 'crevette frite tempura' },
      { e: '🍳', tags: 'oeuf poele jaune' },
      { e: '🥚', tags: 'oeuf coquille' },
      { e: '🐟', tags: 'poisson' },
      { e: '🐠', tags: 'poisson tropical exotique' },
      { e: '🐡', tags: 'fugu poisson globe' },
      { e: '🦐', tags: 'crevette' },
      { e: '🦞', tags: 'homard' },
      { e: '🦀', tags: 'crabe' },
      { e: '🦑', tags: 'calamar encornet' },
      { e: '🐙', tags: 'poulpe pieuvre' },
      { e: '🦪', tags: 'huitre fruits de mer' },
      { e: '🐌', tags: 'escargot' },
      { e: '🐑', tags: 'agneau mouton' },
      { e: '🐂', tags: 'boeuf taureau' },
      { e: '🐖', tags: 'porc cochon' },
      { e: '🐓', tags: 'coq poulet' },
      { e: '🦆', tags: 'canard' },
      { e: '🦃', tags: 'dinde' },
      { e: '🐰', tags: 'lapin' },
      { e: '🦌', tags: 'cerf gibier' },
    ],
  },

  // ─── Légumes & Aromates ────────────────────────────────────────────────────
  {
    id: 'legumes',
    label: 'Légumes',
    icon: '🥕',
    items: [
      { e: '🥕', tags: 'carotte' },
      { e: '🥔', tags: 'pomme de terre patate' },
      { e: '🍠', tags: 'patate douce' },
      { e: '🍅', tags: 'tomate' },
      { e: '🍆', tags: 'aubergine' },
      { e: '🥒', tags: 'concombre cornichon' },
      { e: '🥬', tags: 'salade laitue chou' },
      { e: '🥦', tags: 'brocoli' },
      { e: '🌽', tags: 'mais epi' },
      { e: '🌶', tags: 'piment epice fort' },
      { e: '🫑', tags: 'poivron' },
      { e: '🧄', tags: 'ail' },
      { e: '🧅', tags: 'oignon' },
      { e: '🍄', tags: 'champignon' },
      { e: '🥑', tags: 'avocat' },
      { e: '🫛', tags: 'petits pois' },
      { e: '🫘', tags: 'haricot legume sec' },
      { e: '🌱', tags: 'herbe pousse germe' },
      { e: '🌿', tags: 'herbe aromatique persil ciboulette' },
      { e: '🍀', tags: 'trefle herbe' },
      { e: '☘️', tags: 'trefle' },
      { e: '🌳', tags: 'arbre' },
      { e: '🥖', tags: 'baguette pain' },
      { e: '🫚', tags: 'gingembre racine' },
      { e: '🥥', tags: 'noix de coco' },
      { e: '🌰', tags: 'chataigne marron' },
      { e: '🥜', tags: 'cacahuete arachide' },
    ],
  },

  // ─── Fruits ────────────────────────────────────────────────────────────────
  {
    id: 'fruits',
    label: 'Fruits',
    icon: '🍎',
    items: [
      { e: '🍎', tags: 'pomme rouge' },
      { e: '🍏', tags: 'pomme verte' },
      { e: '🍐', tags: 'poire' },
      { e: '🍊', tags: 'orange clementine mandarine' },
      { e: '🍋', tags: 'citron jaune' },
      { e: '🍌', tags: 'banane' },
      { e: '🍉', tags: 'pasteque' },
      { e: '🍇', tags: 'raisin grappe' },
      { e: '🍓', tags: 'fraise' },
      { e: '🫐', tags: 'myrtille blueberry' },
      { e: '🍒', tags: 'cerise' },
      { e: '🍑', tags: 'peche pavie' },
      { e: '🥭', tags: 'mangue' },
      { e: '🍍', tags: 'ananas' },
      { e: '🥥', tags: 'noix de coco' },
      { e: '🥝', tags: 'kiwi' },
      { e: '🍈', tags: 'melon' },
      { e: '🫒', tags: 'olive' },
      { e: '🍅', tags: 'tomate fruit' },
      { e: '🫛', tags: 'pois cosse' },
    ],
  },

  // ─── Boissons (alcoolisées et non alcoolisées) ─────────────────────────────
  {
    id: 'boissons',
    label: 'Boissons',
    icon: '🍷',
    items: [
      { e: '🍷', tags: 'vin verre rouge' },
      { e: '🥂', tags: 'champagne flute trinquer' },
      { e: '🍾', tags: 'bouteille champagne magnum' },
      { e: '🍺', tags: 'biere chope' },
      { e: '🍻', tags: 'bieres trinquer chopes' },
      { e: '🍸', tags: 'cocktail martini' },
      { e: '🍹', tags: 'cocktail tropical pina colada' },
      { e: '🥃', tags: 'whisky verre rhum cognac' },
      { e: '🍶', tags: 'sake japonais' },
      { e: '☕', tags: 'cafe expresso' },
      { e: '🫖', tags: 'theiere the' },
      { e: '🍵', tags: 'the matcha vert' },
      { e: '🥤', tags: 'soda gobelet boisson' },
      { e: '🧃', tags: 'jus brique pack' },
      { e: '🧉', tags: 'mate calebasse' },
      { e: '🧊', tags: 'glacon glace cube' },
      { e: '🥛', tags: 'lait' },
      { e: '🍼', tags: 'biberon' },
      { e: '🫗', tags: 'verser bouteille liquide' },
      { e: '💧', tags: 'eau goutte' },
      { e: '🥥', tags: 'noix coco lait vegetal' },
    ],
  },

  // ─── Desserts, Pâtisserie, Sucré ───────────────────────────────────────────
  {
    id: 'desserts',
    label: 'Desserts',
    icon: '🍰',
    items: [
      { e: '🍰', tags: 'gateau part shortcake' },
      { e: '🎂', tags: 'gateau anniversaire' },
      { e: '🧁', tags: 'cupcake muffin' },
      { e: '🍮', tags: 'flan creme caramel' },
      { e: '🍩', tags: 'donut beignet' },
      { e: '🍪', tags: 'cookie biscuit' },
      { e: '🥐', tags: 'croissant viennoiserie' },
      { e: '🥖', tags: 'baguette pain' },
      { e: '🍞', tags: 'pain mie tranche' },
      { e: '🥨', tags: 'bretzel' },
      { e: '🥯', tags: 'bagel' },
      { e: '🫓', tags: 'pain plat naan tortilla pita' },
      { e: '🍫', tags: 'chocolat tablette' },
      { e: '🍬', tags: 'bonbon' },
      { e: '🍭', tags: 'sucette' },
      { e: '🍯', tags: 'miel pot' },
      { e: '🍨', tags: 'glace coupe sundae' },
      { e: '🍧', tags: 'glace pilee' },
      { e: '🍦', tags: 'glace cornet softice' },
      { e: '🥧', tags: 'tarte' },
      { e: '🍡', tags: 'dango brochette' },
      { e: '🍢', tags: 'oden brochette' },
      { e: '🥮', tags: 'mooncake gateau lune' },
      { e: '🍥', tags: 'narutomaki kamaboko' },
      { e: '🧇', tags: 'gaufre' },
      { e: '🍿', tags: 'popcorn' },
    ],
  },

  // ─── Épicerie & Condiments ─────────────────────────────────────────────────
  {
    id: 'epicerie',
    label: 'Épicerie',
    icon: '🧂',
    items: [
      { e: '🧂', tags: 'sel salière' },
      { e: '🌶', tags: 'piment epice' },
      { e: '🍯', tags: 'miel pot sucre' },
      { e: '🧈', tags: 'beurre' },
      { e: '🥫', tags: 'conserve boite' },
      { e: '🍶', tags: 'sake bouteille' },
      { e: '🧃', tags: 'jus brique' },
      { e: '🥚', tags: 'oeuf' },
      { e: '🧀', tags: 'fromage' },
      { e: '🍞', tags: 'pain mie' },
      { e: '🥖', tags: 'baguette' },
      { e: '🌾', tags: 'cereale ble' },
      { e: '🍚', tags: 'riz' },
      { e: '🌽', tags: 'mais' },
      { e: '🥜', tags: 'cacahuete fruits secs' },
      { e: '🌰', tags: 'chataigne marron' },
      { e: '🫙', tags: 'pot bocal conserve' },
      { e: '🥛', tags: 'lait' },
      { e: '🧊', tags: 'glacon' },
      { e: '🫗', tags: 'verser liquide' },
    ],
  },

  // ─── Lieux & Service ───────────────────────────────────────────────────────
  {
    id: 'lieux',
    label: 'Lieux & Service',
    icon: '🏨',
    items: [
      { e: '🏨', tags: 'hotel' },
      { e: '🛎', tags: 'reception service cloche concierge' },
      { e: '🌅', tags: 'matin petit dejeuner brunch lever soleil' },
      { e: '🌄', tags: 'aube matin montagne' },
      { e: '🌇', tags: 'crepuscule soir ville' },
      { e: '🌆', tags: 'ville soir crepuscule' },
      { e: '🌃', tags: 'nuit soir diner ville' },
      { e: '🌌', tags: 'nuit etoile galaxie' },
      { e: '🌉', tags: 'pont nuit' },
      { e: '🎭', tags: 'evenement spectacle theatre' },
      { e: '🎪', tags: 'evenement cirque banquet' },
      { e: '🎤', tags: 'micro musique' },
      { e: '🎵', tags: 'musique note' },
      { e: '🎶', tags: 'musique notes' },
      { e: '🎺', tags: 'trompette jazz' },
      { e: '🎷', tags: 'saxophone jazz' },
      { e: '🎸', tags: 'guitare' },
      { e: '🎹', tags: 'piano clavier' },
      { e: '🌊', tags: 'mer plage vague' },
      { e: '🏖', tags: 'plage parasol' },
      { e: '⛱', tags: 'parasol plage' },
      { e: '🏔', tags: 'montagne sommet' },
      { e: '⛰', tags: 'montagne' },
      { e: '🏕', tags: 'camping tente' },
      { e: '🌿', tags: 'terrasse jardin verdure' },
      { e: '🪴', tags: 'plante decoration interieur' },
      { e: '🌳', tags: 'arbre exterieur' },
      { e: '🌲', tags: 'sapin foret' },
      { e: '🌴', tags: 'palmier tropical' },
      { e: '🌷', tags: 'tulipe fleur' },
      { e: '🌸', tags: 'fleur cerisier sakura' },
      { e: '🌹', tags: 'rose romantique' },
      { e: '🌺', tags: 'fleur hibiscus' },
      { e: '🌻', tags: 'tournesol' },
      { e: '☀️', tags: 'soleil ete terrasse' },
      { e: '⛅', tags: 'nuageux' },
      { e: '☁️', tags: 'nuage' },
      { e: '🌙', tags: 'lune nuit' },
      { e: '⭐', tags: 'etoile favori' },
      { e: '🪑', tags: 'chaise' },
      { e: '🛋', tags: 'salon canape lounge' },
      { e: '🛏', tags: 'lit chambre' },
      { e: '🚪', tags: 'porte entree' },
      { e: '🪟', tags: 'fenetre' },
      { e: '🛁', tags: 'baignoire spa' },
      { e: '🚿', tags: 'douche' },
      { e: '🧖', tags: 'spa sauna hammam' },
    ],
  },

  // ─── Activités, Événements, Loisirs ────────────────────────────────────────
  {
    id: 'activites',
    label: 'Activités',
    icon: '🎉',
    items: [
      { e: '🎉', tags: 'fete celebration' },
      { e: '🎊', tags: 'fete confettis' },
      { e: '🎈', tags: 'ballon anniversaire' },
      { e: '🎁', tags: 'cadeau' },
      { e: '🎀', tags: 'noeud ruban' },
      { e: '🎂', tags: 'gateau anniversaire' },
      { e: '🥳', tags: 'fete celebration visage' },
      { e: '💐', tags: 'bouquet fleurs' },
      { e: '🌹', tags: 'rose' },
      { e: '🎄', tags: 'sapin noel' },
      { e: '🎃', tags: 'citrouille halloween' },
      { e: '🎆', tags: 'feu artifice' },
      { e: '🎇', tags: 'etincelles' },
      { e: '✨', tags: 'etoiles brillant special magique' },
      { e: '🪅', tags: 'pinata fete' },
      { e: '🪩', tags: 'boule disco soiree' },
      { e: '💃', tags: 'danseuse danse' },
      { e: '🕺', tags: 'danseur danse' },
      { e: '🎭', tags: 'theatre spectacle' },
      { e: '🎨', tags: 'art peinture palette' },
      { e: '🖌', tags: 'pinceau peinture' },
      { e: '🎬', tags: 'cinema clap film' },
      { e: '🎯', tags: 'cible objectif' },
      { e: '⚽', tags: 'football ballon' },
      { e: '🏀', tags: 'basketball' },
      { e: '🎾', tags: 'tennis' },
      { e: '🏐', tags: 'volleyball' },
      { e: '🏈', tags: 'football americain' },
      { e: '⚾', tags: 'baseball' },
      { e: '🏓', tags: 'ping pong' },
      { e: '🏸', tags: 'badminton' },
      { e: '🥇', tags: 'medaille or premier' },
      { e: '🥈', tags: 'medaille argent deuxieme' },
      { e: '🥉', tags: 'medaille bronze' },
      { e: '🏆', tags: 'trophee gagnant' },
      { e: '🎖', tags: 'medaille militaire' },
      { e: '🎲', tags: 'de jeu' },
      { e: '🎰', tags: 'machine sous casino' },
      { e: '♠️', tags: 'pique cartes' },
      { e: '♥️', tags: 'coeur cartes' },
      { e: '♦️', tags: 'carreau cartes' },
      { e: '♣️', tags: 'trefle cartes' },
    ],
  },

  // ─── Visages & Émotions ────────────────────────────────────────────────────
  {
    id: 'visages',
    label: 'Visages & Émotions',
    icon: '😀',
    items: [
      { e: '😀', tags: 'sourire visage joie' },
      { e: '😃', tags: 'sourire joie' },
      { e: '😄', tags: 'rire joie' },
      { e: '😁', tags: 'sourire dents' },
      { e: '😆', tags: 'rire' },
      { e: '😅', tags: 'rire gene sueur' },
      { e: '🤣', tags: 'mort de rire' },
      { e: '😂', tags: 'larmes de joie' },
      { e: '🙂', tags: 'sourire neutre' },
      { e: '🙃', tags: 'envers' },
      { e: '😉', tags: 'clin oeil' },
      { e: '😊', tags: 'sourire content' },
      { e: '😇', tags: 'ange aureole' },
      { e: '🥰', tags: 'coeurs amour' },
      { e: '😍', tags: 'yeux coeurs amoureux' },
      { e: '🤩', tags: 'etoiles wow' },
      { e: '😘', tags: 'bisou' },
      { e: '😋', tags: 'gourmand miam' },
      { e: '😛', tags: 'langue' },
      { e: '🤤', tags: 'bave gourmand' },
      { e: '😎', tags: 'lunettes cool' },
      { e: '🤓', tags: 'lunettes nerd' },
      { e: '🧐', tags: 'monocle pense' },
      { e: '🤔', tags: 'reflechi pense' },
      { e: '😴', tags: 'dort sommeil' },
      { e: '😪', tags: 'fatigue' },
      { e: '🥱', tags: 'baille' },
      { e: '😵‍💫', tags: 'etourdi confus' },
      { e: '🤯', tags: 'tete explose' },
      { e: '🥺', tags: 'supplice yeux' },
      { e: '😢', tags: 'larme triste' },
      { e: '😭', tags: 'pleure' },
      { e: '😡', tags: 'colere' },
      { e: '🤬', tags: 'jure colere' },
      { e: '🤗', tags: 'cailin' },
      { e: '🫶', tags: 'coeur mains' },
      { e: '👍', tags: 'pouce haut ok' },
      { e: '👎', tags: 'pouce bas non' },
      { e: '👏', tags: 'applaudissements bravo' },
      { e: '🙌', tags: 'celebration mains' },
      { e: '🙏', tags: 'priere merci stp' },
      { e: '💪', tags: 'biceps force' },
      { e: '✌️', tags: 'paix victoire' },
      { e: '🤞', tags: 'doigts croises chance' },
      { e: '🤝', tags: 'poignee main accord' },
      { e: '👋', tags: 'salut au revoir' },
      { e: '❤️', tags: 'coeur rouge amour' },
      { e: '🧡', tags: 'coeur orange' },
      { e: '💛', tags: 'coeur jaune' },
      { e: '💚', tags: 'coeur vert' },
      { e: '💙', tags: 'coeur bleu' },
      { e: '💜', tags: 'coeur violet' },
      { e: '🖤', tags: 'coeur noir' },
      { e: '🤍', tags: 'coeur blanc' },
      { e: '💔', tags: 'coeur brise' },
      { e: '💯', tags: 'cent parfait' },
    ],
  },

  // ─── Animaux ───────────────────────────────────────────────────────────────
  {
    id: 'animaux',
    label: 'Animaux',
    icon: '🐔',
    items: [
      { e: '🐔', tags: 'poule' },
      { e: '🐓', tags: 'coq' },
      { e: '🐣', tags: 'poussin oeuf' },
      { e: '🐥', tags: 'poussin' },
      { e: '🦆', tags: 'canard' },
      { e: '🦢', tags: 'cygne' },
      { e: '🦃', tags: 'dinde' },
      { e: '🐂', tags: 'taureau boeuf' },
      { e: '🐄', tags: 'vache' },
      { e: '🐮', tags: 'tete vache' },
      { e: '🐖', tags: 'cochon porc' },
      { e: '🐷', tags: 'tete cochon' },
      { e: '🐑', tags: 'mouton agneau' },
      { e: '🐐', tags: 'chevre' },
      { e: '🐰', tags: 'lapin' },
      { e: '🐇', tags: 'lapin' },
      { e: '🦌', tags: 'cerf gibier' },
      { e: '🐗', tags: 'sanglier' },
      { e: '🦬', tags: 'bison' },
      { e: '🐴', tags: 'cheval' },
      { e: '🐎', tags: 'cheval course' },
      { e: '🐶', tags: 'chien' },
      { e: '🐱', tags: 'chat' },
      { e: '🐠', tags: 'poisson' },
      { e: '🐟', tags: 'poisson' },
      { e: '🐢', tags: 'tortue' },
      { e: '🦞', tags: 'homard' },
      { e: '🦀', tags: 'crabe' },
      { e: '🦐', tags: 'crevette' },
      { e: '🦑', tags: 'calamar' },
      { e: '🐙', tags: 'pieuvre poulpe' },
      { e: '🦪', tags: 'huitre' },
      { e: '🐝', tags: 'abeille' },
      { e: '🦋', tags: 'papillon' },
    ],
  },

  // ─── Symboles utiles ───────────────────────────────────────────────────────
  {
    id: 'symboles',
    label: 'Symboles',
    icon: '⭐',
    items: [
      { e: '⭐', tags: 'etoile favori' },
      { e: '🌟', tags: 'etoile brillante' },
      { e: '✨', tags: 'etoiles brillant magique special' },
      { e: '💫', tags: 'etoile filante' },
      { e: '🔥', tags: 'feu chaud tendance' },
      { e: '❄️', tags: 'froid neige congelation' },
      { e: '⚡', tags: 'eclair energie' },
      { e: '☀️', tags: 'soleil chaud' },
      { e: '🌈', tags: 'arc en ciel' },
      { e: '💧', tags: 'goutte eau' },
      { e: '🌊', tags: 'vague mer' },
      { e: '⛅', tags: 'nuageux' },
      { e: '☁️', tags: 'nuage' },
      { e: '🪐', tags: 'planete saturne' },
      { e: '🌍', tags: 'terre europe afrique' },
      { e: '🌎', tags: 'terre amerique' },
      { e: '🌏', tags: 'terre asie' },
      { e: '♻️', tags: 'recyclage' },
      { e: '✅', tags: 'check oui valide' },
      { e: '❌', tags: 'croix non erreur' },
      { e: '⛔', tags: 'interdit stop' },
      { e: '🚫', tags: 'interdit' },
      { e: '⚠️', tags: 'avertissement attention' },
      { e: '🆕', tags: 'nouveau new' },
      { e: '🆙', tags: 'up mise a jour' },
      { e: '🆓', tags: 'gratuit free' },
      { e: '🅾️', tags: 'o' },
      { e: '💯', tags: 'cent parfait' },
      { e: '🔝', tags: 'top haut' },
      { e: '🔟', tags: 'dix' },
      { e: '#️⃣', tags: 'diese hashtag' },
      { e: '➕', tags: 'plus ajouter' },
      { e: '➖', tags: 'moins soustraire' },
      { e: '✖️', tags: 'multiplication x' },
      { e: '➗', tags: 'division' },
      { e: '🟢', tags: 'cercle vert ok' },
      { e: '🔴', tags: 'cercle rouge erreur' },
      { e: '🟡', tags: 'cercle jaune attention' },
      { e: '🔵', tags: 'cercle bleu' },
      { e: '🟣', tags: 'cercle violet' },
      { e: '⚫', tags: 'cercle noir' },
      { e: '⚪', tags: 'cercle blanc' },
      { e: '🟠', tags: 'cercle orange' },
      { e: '🔶', tags: 'losange orange' },
      { e: '🔷', tags: 'losange bleu' },
    ],
  },

  // ─── Objets, Outils, Gestion ───────────────────────────────────────────────
  {
    id: 'objets',
    label: 'Objets & Gestion',
    icon: '📦',
    items: [
      { e: '📦', tags: 'colis carton stockage' },
      { e: '📥', tags: 'entrant boite reception' },
      { e: '📤', tags: 'sortant boite envoi' },
      { e: '📨', tags: 'enveloppe message' },
      { e: '📧', tags: 'email mail' },
      { e: '🗂', tags: 'classeur dossier onglets' },
      { e: '📁', tags: 'dossier' },
      { e: '📂', tags: 'dossier ouvert' },
      { e: '🗃', tags: 'classeur archive' },
      { e: '🗄', tags: 'meuble archive classeur' },
      { e: '🗑', tags: 'poubelle supprimer' },
      { e: '📋', tags: 'presse papier liste' },
      { e: '📝', tags: 'note ecriture crayon' },
      { e: '📑', tags: 'document onglet' },
      { e: '📊', tags: 'graphique barre statistiques' },
      { e: '📈', tags: 'graphique hausse' },
      { e: '📉', tags: 'graphique baisse' },
      { e: '🧾', tags: 'recu facture ticket' },
      { e: '💰', tags: 'argent sac' },
      { e: '💵', tags: 'billet dollar' },
      { e: '💶', tags: 'euro billet' },
      { e: '💷', tags: 'livre sterling' },
      { e: '💴', tags: 'yen' },
      { e: '💳', tags: 'carte bancaire credit' },
      { e: '🪙', tags: 'piece monnaie' },
      { e: '🛒', tags: 'panier courses chariot' },
      { e: '🛍', tags: 'sac shopping' },
      { e: '🏷', tags: 'etiquette prix' },
      { e: '🪪', tags: 'carte identite' },
      { e: '📞', tags: 'telephone fixe' },
      { e: '📱', tags: 'mobile smartphone' },
      { e: '💻', tags: 'ordinateur portable laptop' },
      { e: '🖥', tags: 'ordinateur bureau' },
      { e: '⌨️', tags: 'clavier' },
      { e: '🖱', tags: 'souris' },
      { e: '🖨', tags: 'imprimante' },
      { e: '📷', tags: 'appareil photo' },
      { e: '📸', tags: 'flash photo' },
      { e: '🎥', tags: 'camera cinema' },
      { e: '🎬', tags: 'clap film' },
      { e: '⚙️', tags: 'parametre reglage engrenage' },
      { e: '🔧', tags: 'cle outil reparation' },
      { e: '🔨', tags: 'marteau' },
      { e: '🪛', tags: 'tournevis' },
      { e: '🪜', tags: 'echelle' },
      { e: '📐', tags: 'equerre regle' },
      { e: '📏', tags: 'regle' },
      { e: '✂️', tags: 'ciseaux' },
      { e: '📌', tags: 'epingle' },
      { e: '📍', tags: 'epingle localisation' },
      { e: '🧷', tags: 'epingle securite' },
      { e: '🧰', tags: 'boite outils' },
      { e: '🔑', tags: 'cle' },
      { e: '🗝', tags: 'cle ancienne' },
      { e: '🔒', tags: 'cadenas ferme' },
      { e: '🔓', tags: 'cadenas ouvert' },
      { e: '🛡', tags: 'bouclier protection' },
      { e: '⏰', tags: 'reveil horloge' },
      { e: '⏱', tags: 'chronometre' },
      { e: '⏲', tags: 'minuteur' },
      { e: '🕐', tags: 'horloge une heure' },
      { e: '📅', tags: 'calendrier' },
      { e: '📆', tags: 'calendrier date' },
      { e: '🗓', tags: 'calendrier spiral' },
      { e: '🔔', tags: 'cloche notification' },
      { e: '🔕', tags: 'cloche muet' },
      { e: '🔆', tags: 'lumineux luminosite' },
      { e: '💡', tags: 'idee ampoule' },
      { e: '🔦', tags: 'lampe torche' },
      { e: '🕯', tags: 'bougie' },
      { e: '🪔', tags: 'lampe huile diya' },
      { e: '🧴', tags: 'flacon lotion' },
      { e: '🧹', tags: 'balai menage' },
      { e: '🧺', tags: 'panier osier' },
      { e: '🧻', tags: 'papier rouleau' },
      { e: '🚽', tags: 'toilettes' },
    ],
  },

  // ─── Drapeaux Pays (origines produits) ─────────────────────────────────────
  {
    id: 'pays',
    label: 'Pays',
    icon: '🇫🇷',
    items: [
      { e: '🇫🇷', tags: 'france francais' },
      { e: '🇮🇹', tags: 'italie italien' },
      { e: '🇪🇸', tags: 'espagne espagnol' },
      { e: '🇵🇹', tags: 'portugal portugais' },
      { e: '🇩🇪', tags: 'allemagne allemand' },
      { e: '🇧🇪', tags: 'belgique belge' },
      { e: '🇨🇭', tags: 'suisse' },
      { e: '🇱🇺', tags: 'luxembourg' },
      { e: '🇳🇱', tags: 'pays bas hollande' },
      { e: '🇬🇧', tags: 'royaume uni angleterre uk' },
      { e: '🇮🇪', tags: 'irlande' },
      { e: '🇬🇷', tags: 'grece grec' },
      { e: '🇹🇷', tags: 'turquie turc' },
      { e: '🇲🇦', tags: 'maroc marocain' },
      { e: '🇩🇿', tags: 'algerie algerien' },
      { e: '🇹🇳', tags: 'tunisie tunisien' },
      { e: '🇱🇧', tags: 'liban libanais' },
      { e: '🇮🇱', tags: 'israel israelien' },
      { e: '🇪🇬', tags: 'egypte egyptien' },
      { e: '🇮🇳', tags: 'inde indien' },
      { e: '🇯🇵', tags: 'japon japonais' },
      { e: '🇨🇳', tags: 'chine chinois' },
      { e: '🇰🇷', tags: 'coree coreen' },
      { e: '🇹🇭', tags: 'thailande thai' },
      { e: '🇻🇳', tags: 'vietnam vietnamien' },
      { e: '🇲🇽', tags: 'mexique mexicain' },
      { e: '🇧🇷', tags: 'bresil bresilien' },
      { e: '🇦🇷', tags: 'argentine argentin' },
      { e: '🇺🇸', tags: 'etats unis americain usa' },
      { e: '🇨🇦', tags: 'canada canadien' },
      { e: '🇦🇺', tags: 'australie australien' },
      { e: '🇳🇿', tags: 'nouvelle zelande' },
      { e: '🇿🇦', tags: 'afrique sud sud africain' },
      { e: '🇸🇳', tags: 'senegal senegalais' },
      { e: '🇨🇮', tags: 'cote ivoire ivoirien' },
      { e: '🇪🇺', tags: 'union europeenne ue europe' },
    ],
  },
]

// Index plat pour la recherche : aplatit tous les groupes en une seule liste.
// Calculé une seule fois au module load.
export const ALL_EMOJIS = EMOJI_GROUPS.flatMap(g =>
  g.items.map(item => ({ ...item, groupId: g.id }))
)
